# Generated by Django 4.1.7 on 2023-02-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niveau1",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Niveau 1"
            ),
        ),
        migrations.AlterField(
            model_name="niveau2",
            name="niveau1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveau2",
                to="stock.niveau1",
                verbose_name="Niveau 2",
            ),
        ),
        migrations.AlterField(
            model_name="niveau3",
            name="niveau2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveau3",
                to="stock.niveau2",
                verbose_name="Niveau 3",
            ),
        ),
        migrations.AlterField(
            model_name="niveau4",
            name="niveau3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveau4",
                to="stock.niveau3",
                verbose_name="Niveau 4",
            ),
        ),
        migrations.AlterField(
            model_name="niveau5",
            name="niveau4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveau5",
                to="stock.niveau4",
                verbose_name="Niveau 5",
            ),
        ),
    ]
