# Generated by Django 4.1.7 on 2023-03-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="nom_prenom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
