# Generated by Django 4.1.7 on 2023-02-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_remove_commande_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="transport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.transporteur",
            ),
        ),
    ]
