# Generated by Django 4.1.7 on 2023-02-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_niveau1_name_alter_niveau2_niveau1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transporteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_transp",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nom entreprise",
                    ),
                ),
                (
                    "coordonn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="coordonnées",
                    ),
                ),
                (
                    "type_trans",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Type de livraison",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commande",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "en cours de traitement"),
                    ("expeded", "expédiée"),
                    ("cancel", "annulée"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="name_dest",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nom et Prenom du destinataire",
            ),
        ),
        migrations.CreateModel(
            name="Suivi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_suivi", models.CharField(blank=True, max_length=100, null=True)),
                ("date_expedition", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("transit", "en transit"), ("ok", "livré")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.commande",
                    ),
                ),
                (
                    "transporteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.transporteur",
                    ),
                ),
            ],
        ),
    ]
