# Generated by Django 4.1.7 on 2023-02-27 18:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_remove_transporteur_coordonn_transporteur_coordonn1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporteur",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Numero de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Numero de téléphone",
            ),
        ),
    ]
