# Generated by Django 4.1.7 on 2023-02-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_transporteur_phone_number_alter_client_telephone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client", old_name="telephone", new_name="phone_number",
        ),
    ]
